### ISSUE TITLE
wrong evaluation resolution

### ISSUE THREAD

**Issue by LuizGuzzo** [mic-rud/GuidedDecoding#13]
I believe I have found a small flaw in the code. In the validation part, as well as in the inference calculation, you're using the reduced resolution of 240x320 instead of the original resolution of 480x640. This happens because when initializing self.test_loader, you're initializing it with the reduced resolution, so when you ask it to return the prediction to the original size of the ground truth (GT), it is based on the already reduced resolution. To fix this, you just need to change the resolution parameter of the self.test_loader variable to "full" (resolution = "full"). This way, the program will load the dataset with the full resolution, and during validation, it will only reduce the image to fit into the network and return a prediction that will be expanded to the resolution of the GT. With this change, the calculation will be correct, using the GT and pred at the resolution of 480x640.

**Comment by mic-rud** [comment]
Thanks for the note. I just checked the code, but the dataloader does not perform any resizing (The resolution argument is therefore not required and does not change anything). 
As a result, evaluation and metrics are always performed on the full resolution depth maps.
