### ISSUE TITLE
parameters donot match in metrics.py file

### ISSUE THREAD

**Issue by styygaoo** [mic-rud/GuidedDecoding#14]
In metrics.py file,

line 98 - 103, i.e. when invoking the update() method, 
        avg.update(
            self.sum_irmse / self.count, self.sum_imae / self.count,
            self.sum_mse / self.count, self.sum_rmse / self.count, self.sum_mae / self.count,
            self.sum_rmse_log / self.count, self.sum_absrel / self.count, self.sum_lg10 / self.count,
            self.sum_delta1 / self.count, self.sum_delta2 / self.count, self.sum_delta3 / self.count,
            self.sum_gpu_time / self.count, self.sum_data_time / self.count)

the order of the passed parameters is irmse, imae, mse, rmse, **mae, rmse_log**..........

However, in the line 33 - 39, i.e. the method of update() of class Result, 
    def update(self, irmse, imae, mse, rmse, rmse_log, mae, absrel, lg10, delta1, delta2, delta3, gpu_time, data_time):
        self.irmse, self.imae = irmse, imae
        self.mse, self.rmse, self.mae = mse, rmse, mae
        self.rmse_log = rmse_log
        self.absrel, self.lg10 = absrel, lg10
        self.delta1, self.delta2, self.delta3 = delta1, delta2, delta3
        self.data_time, self.gpu_time = data_time, gpu_time

the order of received parameters is irmse, imae, mse, rmse, **rmse_log, mae**,...............

the order of rmse_log and mae does not match!

That is my observation. Do I miss something?

**Comment by mic-rud** [comment]
You are right!
Never looked at rmse_log and mae, so we didn't notice. It's fixed now.
Thank you for bringing this to attention!!
