### ISSUE TITLE
Model Quantization

### ISSUE THREAD

**Issue by LuizGuzzo** [mic-rud/GuidedDecoding#15]
I would like to know how the model quantization is done. Pytorch typically uses float32 for models, however, in your paper, you state that you quantized to float16. I'm new to this process, could you tell me how you did this?

**Comment by mic-rud** [comment]
TensoRT allows conversion of model weigths to float16, reducing memory consumption and speeding up computation.

In general, the precision of float16 is still enough to not affect the results of the model. 
However, the word quantization in the paper might have been inappropriate in the paper, I would rather describe it as **conversion** to float16 in hindsight.
