### ISSUE TITLE
Encoder using Mobilnet V2

### ISSUE THREAD

**Issue by JiSuanJiDaWang** [mic-rud/GuidedDecoding#4]
Hi, really impressive work! I want to use the MobilenetV2 as the encoder in your network, but the output of the mobilenet does not quit match the input of your encoder. I saw on your paper you did experiment on the MobilenetV2. Did you use upsampling and change the number of channel before the decoder or did you use a different decoder with more GUB than that in your paper? Could you give me some information? Thanks

**Comment by mic-rud** [comment]
Thank you for your interest! We used MobileNetV2 in combination with 2 Upsample Layers as described in FastDepth (https://github.com/dwofk/fast-depth), resulting in a feature map of 1/8 * h x 1/8 * w x 6. After that, 3 GUBs were used as for the DDRNet Version. 

If you decide to "shorten" MobileNet and use GUBs on an intermediate feature map of the backbone, I would be very happy if you let me know about the results!

**Comment by JiSuanJiDaWang** [comment]
Thanks!
